In [1]:
import numpy as np
from numpy_vectorized_string_filtering import numpy_isin
import pandas as pd
from faker import Faker

In [2]:
faker = Faker()
Faker.seed(0)

In [3]:
ndata = 10

def create_filtered_column_with_numpy(
    test_df = pd.DataFrame(
        {
            'description': [f'description {i}' for i in range(ndata)]*5
        }
    )
):
    test_df['filtered_description'] = numpy_isin(
        test_df['description'].values,
        [
            'description 0',
            'description 3',
            'description 9', 
        ]
    )
    return test_df

def create_filtered_column_with_pandas(
    test_df = pd.DataFrame(
        {
            'description': [f'description {i}' for i in range(ndata)]*5
        }
    )
):
    test_df['filtered_description'] = test_df['description']
    test_df.loc[
        ~test_df['description'].isin(
            [
                'description 0',
                'description 3',
                'description 9', 
            ]
        ),
        'filtered_description'
    ] = np.nan
    return test_df

In [4]:
create_filtered_column_with_numpy()

      description filtered_description
0   description 0        description 0
1             NaN                  NaN
2             NaN                  NaN
3   description 3        description 3
4             NaN                  NaN
5             NaN                  NaN
6             NaN                  NaN
7             NaN                  NaN
8             NaN                  NaN
9   description 9        description 9
10  description 0        description 0
11            NaN                  NaN
12            NaN                  NaN
13  description 3        description 3
14            NaN                  NaN
15            NaN                  NaN
16            NaN                  NaN
17            NaN                  NaN
18            NaN                  NaN
19  description 9        description 9
20  description 0        description 0
21            NaN                  NaN
22            NaN                  NaN
23  description 3        description 3
24            NaN                  NaN
25            NaN                  NaN
26            NaN                  NaN
27            NaN                  NaN
28            NaN                  NaN
29  description 9        description 9
30  description 0        description 0
31            NaN                  NaN
32            NaN                  NaN
33  description 3        description 3
34            NaN                  NaN
35            NaN                  NaN
36            NaN                  NaN
37            NaN                  NaN
38            NaN                  NaN
39  description 9        description 9
40  description 0        description 0
41            NaN                  NaN
42            NaN                  NaN
43  description 3        description 3
44            NaN                  NaN
45            NaN                  NaN
46            NaN                  NaN
47            NaN                  NaN
48            NaN                  NaN
49  description 9        description 9

In [5]:
create_filtered_column_with_pandas()

      description filtered_description
0   description 0        description 0
1   description 1                  NaN
2   description 2                  NaN
3   description 3        description 3
4   description 4                  NaN
5   description 5                  NaN
6   description 6                  NaN
7   description 7                  NaN
8   description 8                  NaN
9   description 9        description 9
10  description 0        description 0
11  description 1                  NaN
12  description 2                  NaN
13  description 3        description 3
14  description 4                  NaN
15  description 5                  NaN
16  description 6                  NaN
17  description 7                  NaN
18  description 8                  NaN
19  description 9        description 9
20  description 0        description 0
21  description 1                  NaN
22  description 2                  NaN
23  description 3        description 3
24  description 4                  NaN
25  description 5                  NaN
26  description 6                  NaN
27  description 7                  NaN
28  description 8                  NaN
29  description 9        description 9
30  description 0        description 0
31  description 1                  NaN
32  description 2                  NaN
33  description 3        description 3
34  description 4                  NaN
35  description 5                  NaN
36  description 6                  NaN
37  description 7                  NaN
38  description 8                  NaN
39  description 9        description 9
40  description 0        description 0
41  description 1                  NaN
42  description 2                  NaN
43  description 3        description 3
44  description 4                  NaN
45  description 5                  NaN
46  description 6                  NaN
47  description 7                  NaN
48  description 8                  NaN
49  description 9        description 9

In [6]:
import timeit
setup1 = """
import pandas as pd
from numpy_vectorized_string_filtering import numpy_isin
from __main__ import create_filtered_column_with_numpy
ndata = 10
"""
setup2 = """
import pandas as pd
from __main__ import create_filtered_column_with_pandas
ndata = 10
"""
print(timeit.timeit("create_filtered_column_with_numpy()", setup=setup1, number=100))
print(timeit.timeit("create_filtered_column_with_pandas()", setup=setup2, number=100))

TypeError: '<' not supported between instances of 'float' and 'str'